neverpile-minimal-container-test:
   retain_ip: true
   scale: 1
   start_on_create: true
   health_check:
      response_timeout: 2000
      healthy_threshold: 1
      port: 8080
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: none
      request_line: GET "/" "HTTP/1.0"
      reinitializing_timeout: 60000
