neverpile:
   retain_ip: true
   scale: 4
   start_on_create: true
   health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 8080
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: none
      request_line: GET "/" "HTTP/1.0"
      reinitializing_timeout: 60000
      
elasticsearch:
   retain_ip: true
   scale: 1
   start_on_create: true
   health_check:
      response_timeout: 2000
      healthy_threshold: 1
      port: 9200
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: none
      request_line: GET "/_cluster/health" "HTTP/1.0"
      reinitializing_timeout: 60000
      
cassandra:
   retain_ip: true
   scale: 4
   start_on_create: true
   
spring-boot-admin:
  retain_ip: true
  scale: 1
  start_on_create: true
  health_check:
      response_timeout: 2000
      healthy_threshold: 1
      port: 1001
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: none
      request_line: GET "/login" "HTTP/1.0"
      reinitializing_timeout: 60000
