---
apiVersion: v1
kind: ConfigMap
metadata:
  name: neverpile-es-config
  namespace: neverpile-eureka
  labels:
    com.levigo.service: neverpile
    com.levigo.component: elasticsearch
data:
  elasticsearch.yml: |
    cluster:
      name: ${CLUSTER_NAME:neverpile-test-elastic-cluster}
      #initial_master_nodes: ${ELASTIC_INITIAL_MASTER_NODES}

    discovery:
      type: single-node
      #seed_hosts: ${ELASTIC_SEEDS}

    bootstrap:
      memory_lock: ${MEMORY_LOCK:true}

    node:
      master: ${NODE_MASTER:true}
      data: ${NODE_DATA:true}
      name: ${POD_NAME:true}
      ingest: ${NODE_INGEST:true}
      max_local_storage_nodes: ${MAX_LOCAL_STORAGE_NODES:1}

    path:
      data: /usr/share/elasticsearch/data
      logs: /usr/share/elasticsearch/logs

    http:
      compression: true
      cors:
        enabled: ${HTTP_CORS_ENABLE:true}
        allow-origin: ${HTTP_CORS_ALLOW_ORIGIN:*}
      host: ${POD_IP}
      port: 9200

    network:
      host: ${POD_IP}
    transport:
      host: 127.0.0.1
...
#the default discovery settings are unsuitable for production use; at least one of [discovery.seed_hosts, discovery.seed_providers, cluster.initial_master_nodes] must be configured
#discovery.seed_hosts:
#   - 192.168.1.10:9300
#   - 192.168.1.11
#   - seeds.mydomain.com
#cluster.initial_master_nodes:
#   - master-node-a
#   - master-node-b
#   - master-node-c